import assert from 'node:assert/strict';
const {chromium} = await import(process.env.JODD_PLAYWRIGHT || 'playwright');
const browser = await chromium.launch({channel:'chrome', headless:true});
const page = await browser.newPage({viewport:{width:1280,height:850}});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
await page.route('**/*', r=>new URL(r.request().url()).hostname === '127.0.0.1' ? r.continue() : r.abort());
const waitStatus = text=>page.waitForFunction(t=>document.querySelector('.save-status')?.textContent.includes(t),text);
try {
 await page.goto('http://127.0.0.1:1420/tests/browser/showcase.html');
 await waitStatus('Synced');
 await page.locator('.editor-body').fill('Offline edit saved in account A');
 await waitStatus('Sync pending');
 await page.getByRole('button',{name:'Account B',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.editor-body')?.textContent.includes('Private contents of account B'));
 await waitStatus('Synced');
 await page.getByRole('button',{name:'Account A',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.editor-body')?.textContent.includes('Offline edit saved in account A'));
 await page.getByRole('button',{name:'New note',exact:true}).click();
 await page.locator('.title-input').fill('Browser walkthrough note');
 await page.locator('.editor-body').fill('Created and autosaved without remote access');
 await waitStatus('Sync pending');
 assert.ok(await page.evaluate(()=>window.showcase.rows.some(n=>n.title==='Browser walkthrough note' && n.local_version>=1)));
 await page.screenshot({path:'/tmp/jodd-showcase-autosave.png'});
 const search=page.locator('.search-input');
 await search.fill('slow'); await page.waitForTimeout(250);
 await search.fill('Browser');
 await page.waitForFunction(()=>document.body.textContent.includes('1 results in this account'));
 await page.waitForTimeout(900);
 assert.match(await page.locator('.note-item').innerText(), /Browser walkthrough note/);
 await page.evaluate(()=>window.showcase.failSearch(true));
 await search.fill('failure');
 await page.getByText('Could not search. Please retry.').waitFor();
 await page.screenshot({path:'/tmp/jodd-showcase-search-error.png'});
 await page.evaluate(()=>window.showcase.failSearch(false));
 await search.fill('notebook');
 await page.getByLabel('Search scope').selectOption('all');
 await page.waitForFunction(()=>document.body.textContent.includes('2 results in all accounts'));
 assert.equal(await page.locator('.note-item').count(),2);
 await page.screenshot({path:'/tmp/jodd-showcase-accounts.png'});
 await page.locator('.note-btn').filter({hasText:'Account B notebook'}).click();
 await page.waitForFunction(()=>document.querySelector('.editor-body')?.textContent.includes('Private contents of account B'));
 await waitStatus('Synced');
 await page.locator('.note-btn').filter({hasText:'Account A notebook'}).click();
 await page.waitForFunction(()=>document.querySelector('.editor-body')?.textContent.includes('Offline edit saved in account A'));
 await waitStatus('Sync pending');
 await search.fill('');
 await page.getByRole('button',{name:'Delete note',exact:true}).click();
 await page.getByRole('button',{name:'Cancel',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).evaluate(el=>el===document.activeElement),true);
 await page.screenshot({path:'/tmp/jodd-showcase-delete-confirm.png'});
 await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>window.showcase.calls.filter(c=>c.command==='delete_note').length),0);
 assert.deepEqual(errors,[]);
 console.log(`PASS Chrome ${browser.version()}: create, edit, autosave, reopen/account switch with shared UUID, stale search, search failure, cross-account results, delete cancellation; synthetic IPC only`);
} finally {await browser.close();}
